---

- name: install swift storage packages
  yum: pkg={{ item }} state=installed
  with_items:  redhat_packages_storage

- name: config file for account, container and object
  template: src="{{item}}-server.conf.j2" dest="/etc/swift/{{item}}-server.conf" owner=swift group=swift mode=0640
  with_items:
   - account
   - container
   - object
